### ISSUE TITLE
ipc-socket exposed in the host volume

### ISSUE THREAD

**Issue by steakhutzeee** [qbittorrent/docker-qbittorrent-nox#18]
Hello,

backing up the mounted host volume i noted the presence of an "ipc-socket" in there. Why is this exposed in the volume? 

```
steakhutzeee@dk:/srv/dev-disk-by-label-HC2/AppData/qbittorrent-nox/config/qBittorrent/config$ ll
total 24
-rwxrw----  1 steakhutzeee users  828 Oct  4 21:28 categories.json
srwx------  1 steakhutzeee users    0 Oct  4 21:29 ipc-socket
-rw-rw----  1 steakhutzeee users    0 Oct  4 21:29 lockfile
-rwxrw----  1 steakhutzeee users  201 Oct 11 11:56 qBittorrent-data.conf
-rw-rw----  1 steakhutzeee users 4817 Oct  5 21:40 qBittorrent.conf
drwxrws---+ 2 steakhutzeee users 4096 Oct  4 21:29 rss
-rw-rw----  1 steakhutzeee users    4 Oct  4 18:41 watched_folders.json
```

Actually this file is skipped from the backup because it's not a regular file, but maybe this should be implementation detail and reside inside the container itself instead of the host volume?

**Comment by Chocobo1** [comment]
>Actually this file is skipped from the backup because it's not a regular file,

That is right, just ignore it. When qbt-nox quits, it will be removed.

>but maybe this should be implementation detail and reside inside the container itself instead of the host volume?

qbt recognize per config folder instead of per user (or per machine) so everything it needs will reside in the config folder/path and couldn't do otherwise.
