### ISSUE TITLE
qBittorrent data folder location?

### ISSUE THREAD

**Issue by BastionNtB** [qbittorrent/docker-qbittorrent-nox#21]
Hello! I'm wanting to migrate my existing install to this docker image, however, I'm not seeing a volume path for the BT_Backup or logs folder. This folder is where qBittorrent stores the resume data for existing torrents, and I'd like to be able to migrate it over for a seamless transition.

I might be missing something though, I see you can configure the path to the config folder, which only stores the .conf and a couple other important files, but not the resume data of what torrents are in the client. Any idea on this? Thanks!

**Comment by Chocobo1** [comment]
>however, I'm not seeing a volume path for the BT_Backup or logs folder. 

They will reside in a subfolder within the config folder (`<your_path>/config`).

>I might be missing something though, I see you can configure the path to the config folder, which only stores the .conf and a couple other important files, but not the resume data of what torrents are in the client. Any idea on this? Thanks!

You probably already know the answer if you have tried it out. Anyway, all files/folders related to qbt configuration will reside in their subfolder under `<your_path>/config`.
