### ISSUE TITLE
Automatic Agreement to Legal Notice

### ISSUE THREAD

**Issue by martinlesak** [qbittorrent/docker-qbittorrent-nox#28]
Hi,

I have  modified following line in compose.yaml file:     
- QBT_EULA=agree

but when I hit compose it sill wants to accept *** Legal Notice ***: Press 'y' key to accept and continue...

Is there any way I can define in  compose file my agreement to this? Thank You for any help.

**Comment by Chocobo1** [comment]
>I have modified following line in compose.yaml file:
    QBT_EULA=agree

Here is the documentation: https://github.com/qbittorrent/docker-qbittorrent-nox#environment-variables
>Put `accept` only if you understand and accepted the EULA. 

The magic keyword is `accept`, not `agree`.

**Comment by martinlesak** [comment]
You're right - It works flawlessly.  Thank You for Your help. Issue solved.
