### ISSUE TITLE
Bypass authentication for clients in whitelisted IP subnets DOES NOT work with 0.0.0.0/0

### ISSUE THREAD

**Issue by ebeneezer** [qbittorrent/docker-qbittorrent-nox#33]
Bypass authentication for clients in whitelisted IP subnets DOES NOT work with 0.0.0.0/0

did no one ever checked that? dont you guys betatest?

my oh my...

**Comment by Chocobo1** [comment]
It works correctly for me.
Also you reported to the wrong repo.
