### ISSUE TITLE
Any plan to supply docker image with BTv2 support officially?

### ISSUE THREAD

**Issue by xfl12345** [qbittorrent/docker-qbittorrent-nox#35]

**Comment by ShrirajHegde** [comment]
@Chocobo1 is it possible to provide with a different tag, maybe? Something like  `qbittorrentofficial/qbittorrent-nox:libbtv2` or something like that?

Fedora ships with this: 
```
Qt: 6.6.2
Libtorrent: 2.0.10.0
Boost: 1.81.0
OpenSSL: 3.1.1
zlib: 1.2.13
```
It would be cool to have v2 support atleast for testing.

@Chocobo1 what do you think?

**Comment by Chocobo1** [comment]
>It would be cool to have v2 support atleast for testing.

For testing purpose, we already provide `alpha` tag.

**Comment by ShrirajHegde** [comment]
Okay, I will check it out. I thought it is alpha for Qbittorrent only as libtorrent version is hard-coded in Dockerfile.
