### ISSUE TITLE
Questions about permissions

### ISSUE THREAD

**Issue by ai30328348** [qbittorrent/docker-qbittorrent-nox#39]
I set PGID=1000, PUID=1000, UMASK=770 and then I find that it can't start, and it shows 
[root@localhost ~]# docker-compose up
WARN[0000] /root/docker-compose.yml: `version` is obsolete 
[+] Running 1/1
 ✔ Network root_default       Created                                                                                                                    0.2s 
 ⠋ Container qbittorrent-nox  Created                                                                                                                    0.0s 
Attaching to qbittorrent-nox
qbittorrent-nox  | sed: can't create temp file '/etc/passwdXXXXXX': Read-only file system
qbittorrent-nox  | sed: can't create temp file '/etc/passwdXXXXXX': Read-only file system
qbittorrent-nox  | sed: can't create temp file '/etc/groupXXXXXX': Read-only file system
qbittorrent-nox  | QtLockedFile::lock(): file is not opened
qbittorrent-nox  | 
qbittorrent-nox  | *** Legal Notice ***
qbittorrent-nox  | qBittorrent is a file sharing program. When you run a torrent, its data will be made available to others by means of upload. Any content you share is your sole responsibility.
qbittorrent-nox  | 
qbittorrent-nox  | No further notices will be issued.
qbittorrent-nox  | 
qbittorrent-nox  | Press 'y' key to accept and continue...
y

In addition, when PGID=1000, PUID=1000, UMASK=770 is not set, the web cannot be started, and there is no response when I type 'y', I think it is caused by me setting QBT_EULA="y", but what should be filled in here to accept?

**Comment by Chocobo1** [comment]
>I think it is caused by me setting QBT_EULA="y", but what should be filled in here to accept?

Have you read the manual thoroughly?
https://github.com/qbittorrent/docker-qbittorrent-nox?tab=readme-ov-file#environment-variables
>Put `accept` only if you understand and accepted the EULA. 

----

In addition, you have this problem:
>qbittorrent-nox | sed: can't create temp file '/etc/passwdXXXXXX': Read-only file system
>qbittorrent-nox | sed: can't create temp file '/etc/passwdXXXXXX': Read-only file system
>qbittorrent-nox | sed: can't create temp file '/etc/groupXXXXXX': Read-only file system

And the solution from the manual:
>You can change the User ID (UID) and Group ID (GID) of the qbittorrent-nox process by setting environment variables PUID and PGID respectively. By default they are both set to 1000.
***Note that you will need to remove --read-only flag (when using Docker) or set read_only: false (when using Docker Compose) as they are incompatible with it.***

**Comment by ai30328348** [comment]
Thank you very much, my problem solved
