### ISSUE TITLE
Enable to set additional group

### ISSUE THREAD

**Issue by zhen-huan-hu** [qbittorrent/docker-qbittorrent-nox#4]
Can we add an environment variable to allow adding the container user to additional groups? Docker has the --user and --group-add options that allow this but they are not honored here.

I am asking this because I have a shared drive used by multiple services on my headless Ubuntu server: Bittorrent (previously it was Deluge), Jellyfin, and Samba. Each of these has its own user and group. In order to allow all of these users able to read and write to the shared drive, I created a new group for accessing this drive, added these service users to this group, changed the share drive group owner to this, and then (most importantly) set the permission with the sticky bit (aka 2775) so that files created by these different users inside the shared drive would inherit this shared group (instead of the main group of the user)

Jellyfin is easy to migrate to container because its official image honors both --user and --group-add options. But it became a problem when I tried to containerize BitTorrent daemon and found none of the official image honors the --group-add option and instead all use PUID and PGID.

**Comment by Chocobo1** [comment]
>Can we add an environment variable to allow adding the container user to additional groups? 

Sure, I'm thinking of adding a `PAGID` variable for this use case. I suppose you only require *one* additional group, right? (it is cumbersome to write scripts in a limited environment)

**Comment by zhen-huan-hu** [comment]
Thank you. Yes, for my purpose, one additional group would be sufficient.

Would it be easier to use the `USER` instruction provided by Docker instead of the environment variables to switch user from `root` (thus allow the build-in `--group-add` option that supports adding multiple groups if needed)?

**Comment by Chocobo1** [comment]
I submitted PR #5.
You are welcome to test the image, you can find an x64 image at the bottom of this page: https://github.com/qbittorrent/docker-qbittorrent-nox/actions/runs/4051482223 (the Artifacts section)
Extract the zip and load it into docker with `docker load < filename`.
Here is a preview of the updated Readme.md: https://github.com/Chocobo1/docker-qbittorrent-nox/tree/next#usage

In short, the new environment is named `PAGID` and you can assign secondary group ids to it.

**Comment by zhen-huan-hu** [comment]
I have just tested the image. It worked quite well. I was able to download a file under a folder belonging to PAGID. And with the sticky bits set to the folder, the downloaded file is owned by PAGID instead of PGID while the configuration files were owned by PGID. Thank you.
