### ISSUE TITLE
Allow to change unmask settings for downloads

### ISSUE THREAD

**Issue by zhen-huan-hu** [qbittorrent/docker-qbittorrent-nox#6]
The default umask setting for qBittorrent seems to be `022` which makes the downloaded files carry the permission `644`. I would like to change the umask setting to 002 so that the file permission would be `664` and the directory permission would be `2775`. The `lscr.io/linuxserver/qbittorrent` image does provide a environment variable `UMASK` for this purpose. Can this be implemented in the official image as well?

**Comment by Chocobo1** [comment]
I submitted PR https://github.com/qbittorrent/docker-qbittorrent-nox/pull/7.
You are welcome to test the image, you can find an x64 image at the bottom of this page: https://github.com/qbittorrent/docker-qbittorrent-nox/actions/runs/4073162830 (the Artifacts section)
And here is a preview of the updated Readme.md: https://github.com/Chocobo1/docker-qbittorrent-nox/tree/umask#usage
