### ISSUE TITLE
How to press the key 'y' in the container

### ISSUE THREAD

**Issue by hackenfu** [qbittorrent/docker-qbittorrent-nox#8]
After I finish creating the container, I cannot open the login page. the log of container reads below:
qBittorrent is a file sharing program. When you run a torrent, its data will be made available to others by means of upload. Any content you share is your sole responsibility.

*** Legal Notice ***

No further notices will be issued.

Press 'y' key to accept and continue...
So my question is: how to press the key 'y'. Thanks.

**Comment by hackenfu** [comment]
I tried to use the container console, and press y or 'y', but it shows below:
bash: y: command not found

**Comment by 07h** [comment]
@hackenfu I have the same problem. How do I solve it?

**Comment by hackenfu** [comment]
config the&nbsp;docker-compose.yml
&nbsp; &nbsp; &nbsp; - QBT_EULA=accept
then you will solve the problem

&nbsp;


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qbittorrent/docker-qbittorrent-nox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月8日(星期六) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qbittorrent/docker-qbittorrent-nox] How to press the key 'y' in the container (Issue #8)





 
@hackenfu I have the same problem. How do I solve it?

**Comment by Krojack** [comment]
I'm stuck at this for some reason. I have "QBT_EULA=accept" in my environment. The container started the first time but I wanted to make some changes so I stopped and now it won't start. Gets suck at this every time. I even removed everything and started fresh.

**Comment by Csiszerix** [comment]
I had the same problem, while starting the container. Changing the `-t` flag to `-it` in the `docker run   -t  --name qbittorrent-nox   ...`  solved for me. It enables the interaction with the container's terminal.
